#+options: toc:nil
* Fazang
=Fazang= is a Fortran library for reverse-mode automatic
differentiation, inspired by [[https://mc-stan.org/users/interfaces/math][Stan/Math library]].

** Quick start
=Fazang= provides user-facing variable =var= type. It is the type for dependent and independent variables
of which derivatives will be calculated.
#+begin_src fortran
program var_grad_test
  use fazang ! load Fazang library

  implicit none

  real(rk) :: y, fx_d
  type(var) :: f, sigma, mu

  ! data
  y = 1.3d0

  ! independent variables
  mu = 0.5d0
  sigma = 1.2d0

  ! dependent
  f = -0.5d0 * log(2 * pi)
  f = f - log(sigma)
  f = f - 0.5d0 * ((y - mu) / sigma) ** 2.d0;

  ! use grad() to calculate df/d(mu) and df/d(sigma). Each var's
  ! derivative (also called adjoint) can be access through var%adj().

  call grad(f)
  write(*, *) "df/d(mu): ", adj(mu)
  write(*, *) "df/d(sigma): ", adj(sigma)
end program var_grad_test
#+end_src

** Use =Fazang=
*** Build
    =Fazang= uses =cmake= to build.
    #+begin_src bash
      mkdir build
      cd build
      cmake /path/to/fazang -B. -GNinja -Dtest=ON
      cmake --build .
    #+end_src
    Afterwards one can run the unit tests
    #+begin_src bash
      ctest
    #+end_src
*** Use the library
   =Fazang= can be accessed by =use fazang= module.

   A variable declared =var=
    #+begin_src fortran
      type(var) x
    #+end_src
    can be defined as
    #+begin_src fortran
      x = d           ! using a real64 variable
      x = 3.d0        ! using a constant
    #+end_src

    =Fazang= overloads instrinc arithmatic unary and binary
    functions.

    All the
    downstream variables that depend on a =var= should also be =var=
    #+begin_src fortran
      type(var) x, y
      x = 1.d0
      y = sin(x)
    #+end_src

    The value and the adjoint (derivative) of a =var= can be accessed
    using =val()= and =adj()= functions, respectively.
    #+begin_src fortran
      write(*, *) val(y)   ! equals to sin(x%val())
      write(*, *) adj(y)   ! equals to 0.d0 before any gradient operations
    #+end_src

    =Fazang='s unary and binary functions are =elemental=, so they can
    be extended to arrays.
    #+begin_src fortran
      type(var) a(3), b, c(3), d
      a = ([1.d0, 2.d0, 3.d0])
      b = (0.5d0)
      c = 2.d0 * a
      d = log(b * a * exp(c))
    #+end_src
    To calculate a dependent variable's derivatives, call =grad()= function
    #+begin_src fortran
      call grad(d(2))
    #+end_src
    and access each upstream variable's derivative through =adj()= afterwards.
    #+begin_src fortran
      write(*, *) adj(c)    ! should be [0.0, 1.0, 0.0]
    #+end_src

** Name
The library is named after ancient Chinese philosopher [[https://en.wikipedia.org/wiki/Fazang][Fazang]] (法藏), who
views the cosmos "as an infinite number of interdependent
and interpenetrating parts" (一法为因，万法为果；万法为因，一法为果).
