#+options: toc:nil
* Fazang
=Fazang= is a Fortran library for reverse-mode automatic
differentiation, inspired by [[https://mc-stan.org/users/interfaces/math][Stan/Math library]].

** Quick start
=Fazang= provides user-facing variable =var= type. It is the type for dependent and independent variables
of which derivatives will be calculated.

#+INCLUDE: "ftest.f90" src f90

** Use =Fazang=
*** Build
    =Fazang= uses =cmake= to build. The ~CMakeLists.txt~ file has
    a target ~ftest~ that compiles the above example. User may
    replicate the steps to build new applications.
    #+begin_src bash
      mkdir build
      cd build
      cmake /path/to/fazang -B. -GNinja
      cmake --build .
    #+end_src
    The library also contains option ~test~ so that adding ~-Dtest=ON~
    to the above configuration
    #+begin_src bash
      cmake /path/to/fazang -B. -GNinja -Dtest=ON
    #+end_src
    enables building tests. One can then run the unit tests with
    #+begin_src bash
      ctest
    #+end_src
*** Use the library
   =Fazang= can be accessed by =use fazang= module.

   A variable declared =var=
    #+begin_src fortran
      type(var) x
    #+end_src
    can be defined as
    #+begin_src fortran
      x = d           ! assume "d" is a real64 variable
      x = 3.d0        ! using a constant
    #+end_src

    =Fazang= overloads instrinc arithmatic unary and binary
    functions.

    All the
    downstream variables that depend on a =var= should also be =var=
    #+begin_src fortran
      type(var) x, y
      x = 1.d0
      y = sin(x)
    #+end_src

    The value and the adjoint (derivative) of a =var= can be accessed
    using =val()= and =adj()= functions, respectively.
    #+begin_src fortran
      write(*, *) val(y)   ! equals to sin(val(x))
      write(*, *) adj(y)   ! equals to 0.d0 before any gradient operations
    #+end_src

    =Fazang='s unary and binary functions are =elemental=, so they can
    be extended to arrays.
    #+begin_src fortran
      type(var) a(3), b, c(3), d
      a = ([1.d0, 2.d0, 3.d0])
      b = 0.5d0
      c = 2.d0 * a
      d = log(b * a * exp(c))
    #+end_src
    To calculate a dependent variable's derivatives, call =grad()= function
    #+begin_src fortran
      call grad(d(2))
    #+end_src
    and access each upstream variable's derivative through =adj()= afterwards.
    #+begin_src fortran
      write(*, *) adj(c)    ! should be [0.0, 1.0, 0.0]
    #+end_src

*** Hessian
~Fazang~ provides a "front-over-reverse" approach to calculate
Hessians, through another derived type ~fvar~. The work flow is
similar to ~var~, but one must load module ~fz_fvar~ instead of
~fazang~. First use ~init_deriv~ to initialize
the variable with respect to which that the 2nd-order derivate will be
calculated, then use ~deriv~ (counterpart of ~grad~ ) to calculate 1st- and
2nd-order derivatives. The corresponding function to retrieve hessian is
~adj_dv~.
#+begin_src f90
  use fz_fvar
  ! ...
  call init_deriv(b)
  ! ...
  call deriv(f)
  write(*,*) adj_dv(a)
#+end_src
calculates ~d(df/da)/db~. See the following example (~htest.f90~) for
details:
#+INCLUDE: "htest.f90" src f90

** Name
The library is named after ancient Chinese philosopher [[https://en.wikipedia.org/wiki/Fazang][Fazang]] (法藏), who
views the cosmos "as an infinite number of interdependent
and interpenetrating parts" (一法为因，万法为果；万法为因，一法为果).
