cmake_minimum_required(VERSION 3.28)

function(add_fz_test test_name)
  add_executable(${test_name} test_${test_name}.f90)
  target_link_libraries(${test_name} PRIVATE fz)
  target_include_directories(${test_name} PUBLIC "${PROJECT_SOURCE_DIR}/src")
  add_test(NAME ${test_name} COMMAND ${test_name})
endfunction()

add_fz_test(op1)
add_fz_test(op2)
add_fz_test(vec)
add_fz_test(perf_fd)
add_fz_test(dual)
add_fz_test(fvar_op1)
add_fz_test(fvar_op2)
add_fz_test(fvar_hessian)
add_fz_test(new_op)
add_fz_test(prob)
add_fz_test(perf_rosenbrock)
